CREATE TABLE CATEGORY (
    CATEGORY_CODE VARCHAR2(10) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PRODUCT(
    PRODUCT_CODE VARCHAR2(10) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30) NOT NULL,
    CATEGORY_CODE VARCHAR2(10) NOT NULL CONSTRAINT PRODUCT_CATEGORY_CODE_FK REFERENCES CATEGORY(CATEGORY_CODE),
    PRODUCT_PRICE NUMBER(6) NOT NULL,
    PRODUCT_DETAILS VARCHAR2(150),
    PRODUCT_IMAGE VARCHAR2(50)
);

CREATE TABLE OPTIONS (
    OPTIONS_CODE VARCHAR2(10) PRIMARY KEY,
    OPTIONS_NAME VARCHAR2(30) NOT NULL,
    OPTIONS_PRICE NUMBER(6) NOT NULL,
    OPTIONS_DETAILS VARCHAR2(100),
    OPTIONS_IMAGE VARCHAR2(50)
);

CREATE TABLE TOPPING (
    TOPPING_CODE VARCHAR2(10) PRIMARY KEY,
    OPTIONS_CODE VARCHAR2(10) NOT NULL CONSTRAINT TOPPING_OPTIONS_CODE_FK REFERENCES OPTIONS(OPTIONS_CODE),
    PRODUCT_CODE VARCHAR2(10) NOT NULL CONSTRAINT TOPPING_PRODUCT_CODE_FK REFERENCES PRODUCT(PRODUCT_CODE),
    OPTIONS_IMAGE VARCHAR2(50)
);

CREATE TABLE BUNDLE (
    BUNDLE_CODE VARCHAR2(10) PRIMARY KEY,
    BUNDLE_NAME VARCHAR2(30) NOT NULL,
    BUNDLE_DETAILS VARCHAR2(150),
    BUNDLE_PRICE NUMBER(6) NOT NULL,
    BUNDLE_IMAGE VARCHAR2(50)
);

CREATE TABLE BUNDLE_SUB (
    BUNDLE_SUB_CODE VARCHAR2(10) PRIMARY KEY,
    BUNDLE_CODE VARCHAR2(10) NOT NULL CONSTRAINT BUNDLE_SUB_BUNDLE_CODE_FK REFERENCES BUNDLE(BUNDLE_CODE),
    PRODUCT_CODE VARCHAR2(10) NOT NULL CONSTRAINT BUNDLE_SUB_PRODUCT_CODE_FK REFERENCES PRODUCT(PRODUCT_CODE)
);

CREATE TABLE ORDERS(
    ORDERS_CODE VARCHAR2(10) PRIMARY KEY,
    ORDERS_PRICE NUMBER(8) NOT NULL,
    ORDERS_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE ORDERS_DETAILS (
    ORDERS_DETAILS_CODE VARCHAR2(10) PRIMARY KEY,
    ORDERS_CODE VARCHAR(10) NOT NULL CONSTRAINT ORDERS_DETAILS_ORDERS_CODE_FK REFERENCES ORDERS(ORDERS_CODE),
    PRODUCT_CODE VARCHAR2(10) CONSTRAINT ORDERS_DETAILS_PRODUCT_CODE_FK REFERENCES PRODUCT(PRODUCT_CODE),
    OPTIONS_CODE VARCHAR2(10) CONSTRAINT ORDERS_DETAILS_OPTIONS_CODE_FK REFERENCES OPTIONS(OPTIONS_CODE),
    BUNDLE_CODE VARCHAR2(10) NOT NULL CONSTRAINT ORDERS_DETAILS_BUNDLE_CODE_FK REFERENCES BUNDLE(BUNDLE_CODE),
    ORDERS_DETAILS_QTY NUMBER(2) DEFAULT 1 NOT NULL
);

INSERT INTO CATEGORY VALUES('1000', '버거');
INSERT INTO CATEGORY VALUES('2000', '음료');
INSERT INTO CATEGORY VALUES('3000', '사이드');

INSERT INTO PRODUCT VALUES('1001', '와퍼', '1000', 8000, '와퍼 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('1002', '불고기버거', '1000', 7000, '불고기 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('1003', '치킨버거', '1000', 6500, '치킨 ㅇㅇ', 'URL');

INSERT INTO PRODUCT VALUES('2001', '콜라', '2000', 1000, '콜라 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('2002', '제로콜라', '2000', 2000, '제로콜라 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('2003', '생수', '2000', 800, '생수 ㅇㅇ', 'URL');

INSERT INTO PRODUCT VALUES('3001', '프렌치프라이', '3000', 1700, '감자 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('3002', '양념감자', '3000', 2000, '양념 ㅇㅇ', 'URL');
INSERT INTO PRODUCT VALUES('3003', '바삭킹', '3000', 3000, '치킨 ㅇㅇ', 'URL');

INSERT INTO OPTIONS VALUES('2100', '프렌치프라이-라지', 500, '감자튀김 라지 변경', 'URL');
INSERT INTO OPTIONS VALUES('2101', '콜라-라지', 300, '콜라 라지 변경', 'URL');
INSERT INTO OPTIONS VALUES('2102', '차가운 음료', 300, '온도 변경', 'URL');
